export const migrations = [
  {
    version: 1,
    statements: [
      'CREATE TABLE IF NOT EXISTS goal_categories (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL UNIQUE);',
      'CREATE TABLE IF NOT EXISTS goals (id INTEGER PRIMARY KEY AUTOINCREMENT, categoryId INTEGER NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, createdAt TEXT NOT NULL, FOREIGN KEY(categoryId) REFERENCES goal_categories(id) ON DELETE CASCADE);',

      'CREATE TABLE IF NOT EXISTS project_categories (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL UNIQUE);',
      'CREATE TABLE IF NOT EXISTS projects (id INTEGER PRIMARY KEY AUTOINCREMENT, categoryId INTEGER NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, FOREIGN KEY(categoryId) REFERENCES project_categories(id) ON DELETE CASCADE);',
      'CREATE TABLE IF NOT EXISTS subjects (id INTEGER PRIMARY KEY AUTOINCREMENT, projectId INTEGER NOT NULL, parentSubjectId INTEGER NULL, title TEXT NOT NULL, description TEXT NOT NULL, isDone INTEGER NOT NULL DEFAULT 0, FOREIGN KEY(projectId) REFERENCES projects(id) ON DELETE CASCADE, FOREIGN KEY(parentSubjectId) REFERENCES subjects(id) ON DELETE CASCADE);',

      'CREATE TABLE IF NOT EXISTS task_categories (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL UNIQUE);',
      'CREATE TABLE IF NOT EXISTS tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, categoryId INTEGER NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, importance INTEGER NOT NULL, urgency INTEGER NOT NULL, benefit INTEGER NOT NULL, priorityScore INTEGER NOT NULL, isDone INTEGER NOT NULL DEFAULT 0, createdAt TEXT NOT NULL, completedAt TEXT NULL, FOREIGN KEY(categoryId) REFERENCES task_categories(id) ON DELETE CASCADE);',

      'CREATE TABLE IF NOT EXISTS recurring_task_categories (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL UNIQUE);',
      'CREATE TABLE IF NOT EXISTS recurring_tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, categoryId INTEGER NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, frequencyType TEXT NOT NULL, timeOfDay TEXT NOT NULL, lastCompletedAt TEXT NULL, nextDueAt TEXT NOT NULL, notificationsEnabled INTEGER NOT NULL DEFAULT 1, FOREIGN KEY(categoryId) REFERENCES recurring_task_categories(id) ON DELETE CASCADE);',

      'CREATE TABLE IF NOT EXISTS daily_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, logDate TEXT NOT NULL, content TEXT NOT NULL, createdAt TEXT NOT NULL);'
    ]
  }
];
